[package]
name = "singer"
version = "0.1.0"
edition = "2021"

description = "Rust Singer SDK"

license = "Apache-2.0"

repository = "https://github.com/dashbook/singer"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
